---
services:
  seadex:
    image: ghcr.io/thaunknown/release-moe:latest
    container_name: seadex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /host/path/to/data:/data
    ports:
      - 59991:59991
    restart: unless-stopped
